"""PaperBroker unit tests: anti-lookahead, fill pricing, fees."""
from __future__ import annotations

from typing import Optional

import pytest

from app.core.clock import SimClock
from app.core.events import (
    NS_PER_SEC,
    Bar,
    Fill,
    Order,
    OrderStatus,
    OrderType,
    OrderUpdate,
    Side,
    Streams,
)
from app.paper.broker import PaperBroker
from tests.helpers import SyncTestBus

T0 = 1_700_000_000 * NS_PER_SEC
INTERVAL_S = 60
BAR_NS = INTERVAL_S * NS_PER_SEC

SLIPPAGE_BPS = 2.0
FEE_BPS = 1.0


@pytest.fixture()
def env() -> tuple[SyncTestBus, SimClock, PaperBroker]:
    clock = SimClock(start_ns=T0)
    bus = SyncTestBus(clock=clock)
    broker = PaperBroker(bus, clock, slippage_bps=SLIPPAGE_BPS, fee_bps=FEE_BPS)
    return bus, clock, broker


def make_bar(
    ts_open: int,
    *,
    symbol: str = "RELIANCE",
    o: float = 100.0,
    h: float = 101.0,
    lo: float = 99.0,
    c: float = 100.5,
) -> Bar:
    return Bar(
        symbol=symbol,
        ts_open=ts_open,
        interval_s=INTERVAL_S,
        open=o,
        high=h,
        low=lo,
        close=c,
        volume=10_000.0,
    )


def make_order(
    order_id: str,
    *,
    symbol: str = "RELIANCE",
    side: Side = Side.BUY,
    qty: float = 10.0,
    order_type: OrderType = OrderType.MARKET,
    limit_price: Optional[float] = None,
) -> Order:
    return Order(
        order_id=order_id,
        intent_id=f"int-{order_id}",
        strategy_id="strat-1",
        symbol=symbol,
        side=side,
        qty=qty,
        order_type=order_type,
        limit_price=limit_price,
    )


def publish_bar(bus: SyncTestBus, bar: Bar) -> None:
    bus.publish(Streams.MD_BARS, bar, ts_event=bar.ts_close)


def publish_order(bus: SyncTestBus, clock: SimClock, order: Order) -> None:
    bus.publish(Streams.EXEC_ORDERS, order, ts_event=clock.now_ns())


def fills(bus: SyncTestBus) -> list[Fill]:
    return [e.decode() for e in bus.stream(Streams.EXEC_FILLS)]


def updates(bus: SyncTestBus) -> list[OrderUpdate]:
    return [e.decode() for e in bus.stream(Streams.EXEC_ORDER_UPDATES)]


# ---------------------------------------------------------------- ack


def test_order_is_acked_and_pending(env) -> None:
    bus, clock, broker = env
    publish_order(bus, clock, make_order("ord-1"))

    ups = bus.stream(Streams.EXEC_ORDER_UPDATES)
    assert len(ups) == 1
    update = ups[0].decode()
    assert update.order_id == "ord-1"
    assert update.status is OrderStatus.ACKED
    assert ups[0].ts_event == clock.now_ns()

    assert set(broker.pending) == {"ord-1"}
    assert isinstance(broker.pending["ord-1"], Order)
    assert fills(bus) == []


# ----------------------------------------------------- anti-lookahead


def test_signal_bar_never_fills_its_own_order(env) -> None:
    """The single most important property: an order generated by a bar
    close cannot fill on that bar -- not even when the bar is replayed
    -- and fills on the next bar's open instead."""
    bus, clock, broker = env
    signal_bar = make_bar(T0, o=100.0)
    publish_bar(bus, signal_bar)  # strategy decides on this close
    assert fills(bus) == []

    clock.advance_to(signal_bar.ts_close)  # the order exists only now
    publish_order(bus, clock, make_order("ord-al"))
    assert "ord-al" in broker.pending

    publish_bar(bus, signal_bar)  # replay of the signal bar
    assert fills(bus) == []
    assert "ord-al" in broker.pending

    next_bar = make_bar(T0 + BAR_NS, o=102.0, h=103.0, lo=101.0, c=102.5)
    publish_bar(bus, next_bar)  # ts_open == placed_ts -> eligible
    got = fills(bus)
    assert len(got) == 1
    assert got[0].price == 102.0 * (1 + SLIPPAGE_BPS / 1e4)
    assert got[0].ts_fill == next_bar.ts_open
    assert broker.pending == {}


def test_bar_older_than_order_never_fills(env) -> None:
    bus, clock, broker = env
    clock.advance_to(T0 + 5 * BAR_NS)
    publish_order(bus, clock, make_order("ord-old"))

    publish_bar(bus, make_bar(T0 + 4 * BAR_NS))  # strictly before placed_ts
    assert fills(bus) == []
    assert "ord-old" in broker.pending


# ------------------------------------------------------- market fills


def test_market_buy_pays_slippage_above_open(env) -> None:
    bus, clock, broker = env
    publish_order(bus, clock, make_order("ord-b", side=Side.BUY))
    publish_bar(bus, make_bar(T0, o=100.0))

    got = fills(bus)
    assert len(got) == 1
    assert got[0].price == 100.0 * (1 + SLIPPAGE_BPS / 1e4)
    assert got[0].price > 100.0
    assert got[0].side is Side.BUY
    assert got[0].qty == 10.0


def test_market_sell_pays_slippage_below_open(env) -> None:
    bus, clock, broker = env
    publish_order(bus, clock, make_order("ord-s", side=Side.SELL))
    publish_bar(bus, make_bar(T0, o=100.0))

    got = fills(bus)
    assert len(got) == 1
    assert got[0].price == 100.0 * (1 - SLIPPAGE_BPS / 1e4)
    assert got[0].price < 100.0


# -------------------------------------------------------- limit fills


def test_limit_buy_fills_at_limit_when_bar_trades_through(env) -> None:
    bus, clock, broker = env
    publish_order(
        bus, clock,
        make_order("ord-lb", order_type=OrderType.LIMIT, limit_price=99.5),
    )
    publish_bar(bus, make_bar(T0, o=100.0, h=101.0, lo=99.0))

    got = fills(bus)
    assert len(got) == 1
    assert got[0].price == 99.5  # no slippage on limit fills


def test_limit_buy_gap_down_fills_at_open(env) -> None:
    bus, clock, broker = env
    publish_order(
        bus, clock,
        make_order("ord-lg", order_type=OrderType.LIMIT, limit_price=99.5),
    )
    publish_bar(bus, make_bar(T0, o=98.0, h=99.0, lo=97.5))  # open <= limit

    got = fills(bus)
    assert len(got) == 1
    assert got[0].price == 98.0  # price improvement at the open


def test_limit_buy_stays_pending_when_price_not_reached(env) -> None:
    bus, clock, broker = env
    publish_order(
        bus, clock,
        make_order("ord-lp", order_type=OrderType.LIMIT, limit_price=98.0),
    )
    publish_bar(bus, make_bar(T0, o=100.0, h=101.0, lo=99.0))  # low > limit

    assert fills(bus) == []
    assert "ord-lp" in broker.pending  # GTC: still working

    # It fills later once a bar trades through the limit.
    publish_bar(bus, make_bar(T0 + BAR_NS, o=99.0, h=99.5, lo=97.0))
    got = fills(bus)
    assert len(got) == 1
    assert got[0].price == 98.0
    assert broker.pending == {}


def test_limit_sell_fills_at_limit_when_bar_trades_through(env) -> None:
    bus, clock, broker = env
    publish_order(
        bus, clock,
        make_order(
            "ord-ls", side=Side.SELL, order_type=OrderType.LIMIT, limit_price=100.5
        ),
    )
    publish_bar(bus, make_bar(T0, o=100.0, h=101.0, lo=99.0))

    got = fills(bus)
    assert len(got) == 1
    assert got[0].price == 100.5


def test_limit_sell_gap_up_fills_at_open(env) -> None:
    bus, clock, broker = env
    publish_order(
        bus, clock,
        make_order(
            "ord-lsg", side=Side.SELL, order_type=OrderType.LIMIT, limit_price=100.5
        ),
    )
    publish_bar(bus, make_bar(T0, o=102.0, h=103.0, lo=101.0))  # open >= limit

    got = fills(bus)
    assert len(got) == 1
    assert got[0].price == 102.0


def test_limit_sell_stays_pending_when_price_not_reached(env) -> None:
    bus, clock, broker = env
    publish_order(
        bus, clock,
        make_order(
            "ord-lsp", side=Side.SELL, order_type=OrderType.LIMIT, limit_price=102.0
        ),
    )
    publish_bar(bus, make_bar(T0, o=100.0, h=101.0, lo=99.0))  # high < limit

    assert fills(bus) == []
    assert "ord-lsp" in broker.pending


# ---------------------------------------------------- fees and fills


def test_fees_are_qty_times_price_times_fee_bps(env) -> None:
    bus, clock, broker = env
    publish_order(bus, clock, make_order("ord-f", qty=10.0))
    publish_bar(bus, make_bar(T0, o=100.0))

    got = fills(bus)
    assert len(got) == 1
    assert got[0].fees == 10.0 * got[0].price * FEE_BPS / 1e4
    assert got[0].fees == pytest.approx(0.10002)  # 10 * 100.02 * 1e-4


def test_fill_event_fields_and_filled_update(env) -> None:
    bus, clock, broker = env
    publish_order(bus, clock, make_order("ord-x"))
    bar = make_bar(T0, o=100.0)
    publish_bar(bus, bar)

    got = fills(bus)
    assert len(got) == 1
    fill = got[0]
    assert fill.fill_id == "fill-ord-x-1"
    assert fill.order_id == "ord-x"
    assert fill.intent_id == "int-ord-x"
    assert fill.strategy_id == "strat-1"
    assert fill.symbol == "RELIANCE"
    assert fill.ts_fill == bar.ts_open
    assert fill.qty == 10.0  # full quantity, single fill

    assert [u.status for u in updates(bus)] == [
        OrderStatus.ACKED,
        OrderStatus.FILLED,
    ]
    # Fill is published before the FILLED update.
    fill_idx = next(i for i, e in enumerate(bus.events) if e.type == "Fill")
    filled_idx = next(
        i
        for i, e in enumerate(bus.events)
        if e.type == "OrderUpdate"
        and e.payload["status"] == OrderStatus.FILLED.value
    )
    assert fill_idx < filled_idx
    assert broker.pending == {}

    # Filled orders never fill again on later bars.
    publish_bar(bus, make_bar(T0 + BAR_NS, o=105.0, h=106.0, lo=104.0))
    assert len(fills(bus)) == 1


def test_bar_for_other_symbol_does_not_fill(env) -> None:
    bus, clock, broker = env
    publish_order(bus, clock, make_order("ord-tcs", symbol="TCS"))
    publish_bar(bus, make_bar(T0, symbol="RELIANCE"))

    assert fills(bus) == []
    assert "ord-tcs" in broker.pending


def test_limit_order_without_price_is_rejected(env) -> None:
    bus, clock, broker = env
    publish_order(
        bus, clock,
        make_order("ord-bad", order_type=OrderType.LIMIT, limit_price=None),
    )

    assert [u.status for u in updates(bus)] == [OrderStatus.REJECTED]
    assert broker.pending == {}


def test_multiple_pending_orders_fill_on_one_bar(env) -> None:
    bus, clock, broker = env
    publish_order(bus, clock, make_order("ord-1", side=Side.BUY))
    publish_order(bus, clock, make_order("ord-2", side=Side.SELL, qty=5.0))
    publish_bar(bus, make_bar(T0, o=100.0))

    got = fills(bus)
    assert [f.order_id for f in got] == ["ord-1", "ord-2"]
    assert got[0].price == 100.0 * (1 + SLIPPAGE_BPS / 1e4)
    assert got[1].price == 100.0 * (1 - SLIPPAGE_BPS / 1e4)
    assert broker.pending == {}
